name: damselfly-actions
on: [push]
jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
        include: 
          - os: windows-latest
            command: distwin
          - os: ubuntu-latest
            command: distlinux
          - os: macos-latest
            command: distmac

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      
      - name: Run Electron build
        run: | 
             cd Damselfly.Desktop
             yarn install 
             yarn ${{ matrix.command }} 

      - name: Upload desktop builds for Docker build
        uses: actions/upload-artifact@v1
        with:
          name: Desktop-Dist
          path: Damselfly.Desktop/dist/*.*

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build non-docker Server
        run: sh makeserver.sh

      - name: Upload server builds to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Server-Dist
          path: Damselfly.Web/server/*.zip      

  build-docker:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Download Desktop Builds
        uses: actions/download-artifact@v2
        with:
          name: Desktop-Dist
      - name: Build docker package
        run: sh makedocker.sh
