name: damselfly-actions
on: [push]
jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [mac, linux, windows]
        include: 
          - target: windows
            os: windows-latest
            command: distwin
          - target: linux
            os: ubuntu-latest
            command: distlinux
          - target: mac
            os: macos-latest
            command: distmac

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      
      - name: Run Electron build
        run: | 
             cd Damselfly.Desktop
             yarn install 
             yarn ${{ matrix.command }}

      - name: Upload desktop builds for Docker build
        uses: actions/upload-artifact@v2
        with:
          name: Desktop-Dist
          path: |
                Damselfly.Desktop/dist/*.zip
                Damselfly.Desktop/dist/*.AppImage
          retention-days: 5

  build-server:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [mac, windows, linux, alpine]
        include: 
          - target: windows
            platform: win-x64
            os: ubuntu-latest
            zipname: damselfly-server-win
          - target: linux
            platform: linux-x64
            os: ubuntu-latest
            zipname: damselfly-server-linux
          - target: alpine
            platform: alpine-x64
            os: ubuntu-latest
            zipname: damselfly-server-alpine
          - target: mac
            platform: osx-x64
            os: macos-latest
            zipname: damselfly-server-mac

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Dotnet Build
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: sh buildserver.sh ${{ matrix.platform }} ${{ matrix.zipname }}

      - name: Upload server builds to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Server-Dist
          path: server/*.zip     
          retention-days: 5

  build-docker:
    needs: [build-server, build-desktop]
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [alpine]
        include: 
          - target: alpine
            os: ubuntu-latest
            serverzip: damselfly-server-alpine

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Download Server Build
        uses: actions/download-artifact@v2
        with:
          name: Server-Dist
          path: servers

      - name: Unzip server into publish folder
        run: |
             mkdir publish
             cd publish
             unzip $GITHUB_WORKSPACE/servers/${{ matrix.serverzip }}-*.zip
             cd ..

      - name: Download Desktop Builds into wwwroot folder
        uses: actions/download-artifact@v2
        with:
          name: Desktop-Dist
          path: publish/wwwroot/desktop

      - name: Check publish contents
        run: find publish -type f

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker
        run: sh ./makedocker.sh