name: damselfly-actions
on: [push]
jobs:
  build-desktop:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - run: sh makedesktop.sh
      - name: Upload desktop builds
        uses: actions/upload-artifact@v1
        with:
          name: Desktop-Dist
          path: ./dist/*.zip
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh makeserver.sh
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Desktop Builds
        uses: actions/download-artifact@v2
        with:
          name: Desktop-Dist
      - run: sh makedocker.sh
