name: damselfly-actions
on: [push]
jobs:
  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh makedesktop.sh
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh makeserver.sh
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh makedocker.sh
