name: damselfly-actions
on: [push]
jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
        include: 
          - os: windows-latest
            command: distwin
          - os: ubuntu-latest
            command: distlinux
          - os: macos-latest
            command: distmac

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      
      - name: Run Electron build
        run: | 
             cd Damselfly.Desktop
             yarn install 
             yarn ${{ matrix.command }}
             ls dist

      - name: Upload desktop builds for Docker build
      - uses: actions/upload-artifact@v2
        with:
          name: Desktop-Dist
          path: |
                Damselfly.Desktop/dist/*.zip
                Damselfly.Desktop/dist/*.AppImage
          if-no-files-found: warn

  build-server:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
        include: 
          - os: windows-latest
            netplatform: osx-x64
            zipname: damselfly-server-mac
          - os: ubuntu-latest
            netplatform: win-x64
            zipname: damselfly-server-win
          - os: macos-latest
            netplatform: linux-x64
            zipname: damselfly-server-linux

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Dotnet Build
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
      - run: |
             dotnet publish Damselfly.Web -r ${{ netplatform }} -c Release --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:Version=$version /p:IncludeNativeLibrariesForSelfExtract=true
             cd Damselfly.Web/bin/Release/net5.0/${{ netplatform }}/publish
             zip -r ../../../../../../server/${{ zipname }}-$version.zip *.* -x "*.pdb" 
             cd ../../../../../..

      - name: Upload server builds to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Server-Dist
          path: Damselfly.Web/server/*.zip     

  build-docker:
    needs: [build-server, build-desktop]
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Download Desktop Builds
        uses: actions/download-artifact@v2
        with:
          name: Desktop-Dist
          path: Damselfly.Web/wwwroot/desktop

      - name: Build docker package
        run: sh makedocker.sh
