name: damselfly-actions
on: [push]
jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [mac, linux, windows]
        include: 
          - target: windows
            os: windows-latest
          - target: linux
            os: ubuntu-latest
          - target: mac
            os: macos-latest

    steps:
      - name: Only do this when tagged
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "Hello tag ${{ github.ref }}"

        - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      
      - name: Run Electron build
        run: sh scripts/makedesktop.sh ${{ matrix.target }}

      - name: Upload desktop builds for Docker build
        uses: actions/upload-artifact@v2
        with:
          name: Desktop-Dist
          path: Damselfly.Web/wwwroot/desktop/*.*
          retention-days: 5

  build-server:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [mac, windows, linux, alpine]
        include: 
          - target: windows
            os: ubuntu-latest
          - target: linux
            os: ubuntu-latest
          - target: alpine
            os: ubuntu-latest
          - target: mac
            os: macos-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Dotnet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Run Dotnet Server Build
        run: sh scripts/makeserver.sh ${{ matrix.target }} 

      - name: Upload server builds to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Server-Dist
          path: server/*.zip     
          retention-days: 5

  build-docker:
    needs: [build-server, build-desktop]
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [alpine]
        include: 
          - target: alpine
            os: ubuntu-latest

    steps:        
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Download Server Build
        uses: actions/download-artifact@v2
        with:
          name: Server-Dist
          path: server

      - name: Unzip server into publish folder
        run: |
             mkdir publish
             cd publish
             unzip $GITHUB_WORKSPACE/server/damselfly-server-${{ matrix.target }}-*.zip
             cd ..

      - name: Download Desktop Builds into wwwroot folder
        uses: actions/download-artifact@v2
        with:
          name: Desktop-Dist
          path: publish/wwwroot/desktop

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker
        run: sh scripts/makedocker.sh

